### ISSUE TITLE
File not found random/...

### ISSUE THREAD

**Issue by janinko** [Commonjava/galley#115]
We are sometimes getting this kind of error with some file not existing in folder ``random``. What is the cause? How to deal with it? (Right now we always delete the folder ``random``.)
```
ERROR [org.jboss.da.rest.reports.Reports] (default task-1) Exception thrown during POM analysis: org.jboss.da.communication.pom.PomAnalysisException: org.commonjava.maven.galley.maven.parse.GalleyMavenXMLException: Failed to read: SimpleLocation [uri=http://repo.maven.apache.org/maven2/]:org/jboss/shrinkwrap/resolver/shrinkwrap-resolver-bom/2.1.1/shrinkwrap-resolver-bom-2.1.1.pom. Reason: random/519ba4d0b99f705fb44c8aec750b10983bafe179/org/jboss/shrinkwrap/resolver/shrinkwrap-resolver-bom/2.1.1/shrinkwrap-resolver-bom-2.1.1.pom (Adresář nebo soubor neexistuje)
	at org.jboss.da.communication.pom.PomAnalyzerImpl.readRelationships(PomAnalyzerImpl.java:96)
	at org.jboss.da.communication.pom.PomAnalyzerImpl.readRelationships(PomAnalyzerImpl.java:66)
	at org.jboss.da.communication.pom.PomAnalyzerImpl$Proxy$_$$_WeldClientProxy.readRelationships(Unknown Source)
	at org.jboss.da.communication.scm.impl.SCMConnectorImpl.getDependencyTreeOfRevision(SCMConnectorImpl.java:68)
	at org.jboss.da.communication.scm.impl.SCMConnectorImpl$Proxy$_$$_WeldClientProxy.getDependencyTreeOfRevision(Unknown Source)
	at org.jboss.da.reports.backend.impl.DependencyTreeGeneratorImpl.getDependencyTree(DependencyTreeGeneratorImpl.java:39)
	at org.jboss.da.reports.backend.impl.DependencyTreeGeneratorImpl$Proxy$_$$_WeldClientProxy.getDependencyTree(Unknown Source)
	at org.jboss.da.reports.impl.ReportsGeneratorImpl.getReportFromSCM(ReportsGeneratorImpl.java:92)
	at org.jboss.da.rest.reports.Reports.scmGenerator(Reports.java:102)
	at org.jboss.da.rest.reports.Reports$Proxy$_$$_WeldClientProxy.scmGenerator(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:139)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:295)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:249)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:236)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:395)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:202)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:221)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:285)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:264)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:175)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:202)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:792)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.commonjava.maven.galley.maven.parse.GalleyMavenXMLException: Failed to read: SimpleLocation [uri=http://repo.maven.apache.org/maven2/]:org/jboss/shrinkwrap/resolver/shrinkwrap-resolver-bom/2.1.1/shrinkwrap-resolver-bom-2.1.1.pom. Reason: random/519ba4d0b99f705fb44c8aec750b10983bafe179/org/jboss/shrinkwrap/resolver/shrinkwrap-resolver-bom/2.1.1/shrinkwrap-resolver-bom-2.1.1.pom (Adresář nebo soubor neexistuje)
	at org.commonjava.maven.galley.maven.parse.XMLInfrastructure.parse(XMLInfrastructure.java:466)
	at org.commonjava.maven.galley.maven.parse.MavenPomReader.getDocRef(MavenPomReader.java:206)
	at org.commonjava.maven.galley.maven.parse.MavenPomReader.read(MavenPomReader.java:316)
	at org.commonjava.maven.galley.maven.parse.MavenPomReader.read(MavenPomReader.java:300)
	at org.commonjava.maven.galley.maven.parse.MavenPomReader.assembleImportedInformation(MavenPomReader.java:353)
	at org.commonjava.maven.galley.maven.parse.MavenPomReader.read(MavenPomReader.java:336)
	at org.commonjava.maven.galley.maven.parse.MavenPomReader.read(MavenPomReader.java:300)
	at org.commonjava.maven.galley.maven.parse.MavenPomReader.read(MavenPomReader.java:286)
	at org.jboss.da.communication.pom.GalleyWrapper.getDeps(GalleyWrapper.java:292)
	at org.jboss.da.communication.pom.GalleyWrapper.getAllDependencies(GalleyWrapper.java:268)
	at org.jboss.da.communication.pom.GalleyWrapper.getAllDependencies(GalleyWrapper.java:237)
	at org.jboss.da.communication.pom.PomAnalyzerImpl.readRelationships(PomAnalyzerImpl.java:90)
	... 50 more
Caused by: java.io.FileNotFoundException: random/519ba4d0b99f705fb44c8aec750b10983bafe179/org/jboss/shrinkwrap/resolver/shrinkwrap-resolver-bom/2.1.1/shrinkwrap-resolver-bom-2.1.1.pom (Adresář nebo soubor neexistuje)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at org.commonjava.maven.galley.cache.FileCacheProvider.openInputStream(FileCacheProvider.java:192)
	at org.commonjava.maven.galley.model.Transfer.openInputStream(Transfer.java:146)
	at org.commonjava.maven.galley.model.Transfer.openInputStream(Transfer.java:137)
	at org.commonjava.maven.galley.maven.parse.XMLInfrastructure.parse(XMLInfrastructure.java:461)
	... 61 more
```

**Comment by jdcasey** [comment]
My best guess is that the file is still being written when the xml parser tries to read it. The 'random' location is something peculiar to the DA project, it looks like...underneath that directory, you see a hashed directory name which corresponds to the actual remote source of the POM, then the path within that remote location.

I found this in the Galley FileCacheProvider, which suggests this problem might happen:

https://github.com/Commonjava/galley/blob/galley-0.11.3/core/src/main/java/org/commonjava/maven/galley/cache/FileCacheProvider.java#L192

It's also in the master branch as of this writing.

**Comment by jdcasey** [comment]
@janinko Is this still happening in DA? If so, I wonder if upgrading to the latest galley version (0.13.2 IIRC) would help? Was this a problem with read locking in the FileCacheProvider implementation, I wonder, or something else?

**Comment by janinko** [comment]
Hi, we didn't seen that issue in a while, if we see it again, I'll reopen this.
